### ISSUE TITLE
Bug feature rates

### ISSUE THREAD

**Issue by ArnaudGau** [fmeurou/geocurrency#1]
-  https://api.geocurrency.me/rates/?currency=SEK

ne sors que les rates en base_currency SEK mais pas que les rates avec la currency SEK

- https://api.geocurrency.me/rates/?key=2 

me ressort les clés à null

- https://api.geocurrency.me/rates/?value_date=2020-09-29

Field 'value' expected a number but got '2020-09-29'.

- https://api.geocurrency.me/rates/?value=17
me ressort des value a 40 ou a 0

**Comment by fmeurou** [comment]
Fixed in v.0.2.25

**Comment by ArnaudGau** [comment]
"https://api.geocurrency.me/rates/?key=nombrequinexistepas"
-me renvoie Expected 'RateFilter.key' to return a QuerySet, but got a NoneType instead. il manque juste le retour d'erreur si rien n'est retourné?

https://api.geocurrency.me/rates/?value=4.135
on va peut être devoir mettre des arrondits car ça me renvoie un tableau vide
https://api.geocurrency.me/rates/?value=4.1352042407 fonctionne ou une recherche un peu moins strict à voir
