### ISSUE TITLE
Unité kilogramme manquante bien que definie comme unité de base

### ISSUE THREAD

**Issue by 3bandiste** [fmeurou/geocurrency#6]
https://dev.geocurrency.me/units/SI/units/per_dimension/

Dans le retour d'API pour la masse, on a une base_unit qui ne fait pas partie des units.
Même chose pour l'Aire, le volume et la vitesse en ce qui concerne le SI
`{
    "code": "[mass]",
    "name": "Masse",
    "dimension": "kilogram",
    "base_unit": "kilogram",
    "units": [
      {
        "code": "bag",
        "name": "sac",
        "dimensions": "[[mass]]"
      },
      {
        "code": "scruple",
        "name": "scrupule",
        "dimensions": "[[mass]]"
      },
      {
        "code": "slug",
        "name": "slug",
        "dimensions": "[[mass]]"
      },
      {
        "code": "metric_ton",
        "name": "tonne",
        "dimensions": "[[mass]]"
      },
      {
        "code": "quarter",
        "name": "trimestre",
        "dimensions": "[[mass]]"
      },
      {
        "code": "US_ton",
        "name": "tonne courte",
        "dimensions": "[[mass]]"
      },
      {
        "code": "apothecary_pound",
        "name": "livre d'apothicaire",
        "dimensions": "[[mass]]"
      },
      {
        "code": "atomic_mass_constant",
        "name": "constante de masse atomique",
        "dimensions": "[[mass]]"
      },
      {
        "code": "ton",
        "name": "tonne",
        "dimensions": "[[mass]]"
      },
      {
        "code": "gram",
        "name": "gramme",
        "dimensions": "[[mass]]"
      },
      {
        "code": "dram",
        "name": "drachme",
        "dimensions": "[[mass]]"
      },
      {
        "code": "ounce",
        "name": "once",
        "dimensions": "[[mass]]"
      },
      {
        "code": "troy_pound",
        "name": "livre troy",
        "dimensions": "[[mass]]"
      },
      {
        "code": "US_hundredweight",
        "name": "petit quintal",
        "dimensions": "[[mass]]"
      },
      {
        "code": "apothecary_dram",
        "name": "dram d‘apothicaire",
        "dimensions": "[[mass]]"
      },
      {
        "code": "unified_atomic_mass_unit",
        "name": "unité de masse atomique unifiée",
        "dimensions": "[[mass]]"
      },
      {
        "code": "long_ton",
        "name": "longue tonne",
        "dimensions": "[[mass]]"
      },
      {
        "code": "carat",
        "name": "carat",
        "dimensions": "[[mass]]"
      },
      {
        "code": "electron_mass",
        "name": "masse électronique",
        "dimensions": "[[mass]]"
      },
      {
        "code": "long_hundredweight",
        "name": "long quintal",
        "dimensions": "[[mass]]"
      },
      {
        "code": "proton_mass",
        "name": "masse de protons",
        "dimensions": "[[mass]]"
      },
      {
        "code": "slinch",
        "name": "slinch",
        "dimensions": "[[mass]]"
      },
      {
        "code": "stone",
        "name": "pierre",
        "dimensions": "[[mass]]"
      },
      {
        "code": "apothecary_ounce",
        "name": "once d'apothicaire",
        "dimensions": "[[mass]]"
      },
      {
        "code": "dalton",
        "name": "Dalton",
        "dimensions": "[[mass]]"
      },
      {
        "code": "neutron_mass",
        "name": "masse neutronique",
        "dimensions": "[[mass]]"
      },
      {
        "code": "grain",
        "name": "grain",
        "dimensions": "[[mass]]"
      },
      {
        "code": "UK_hundredweight",
        "name": "long hundredweight",
        "dimensions": "[[mass]]"
      },
      {
        "code": "troy_ounce",
        "name": "once troy",
        "dimensions": "[[mass]]"
      },
      {
        "code": "hundredweight",
        "name": "quintal",
        "dimensions": "[[mass]]"
      },
      {
        "code": "planck_mass",
        "name": "Masse de Planck",
        "dimensions": "[[mass]]"
      },
      {
        "code": "gamma_mass",
        "name": "gamma",
        "dimensions": "[[mass]]"
      },
      {
        "code": "UK_ton",
        "name": "longue tonne",
        "dimensions": "[[mass]]"
      },
      {
        "code": "pound",
        "name": "livre",
        "dimensions": "[[mass]]"
      },
      {
        "code": "pennyweight",
        "name": "pennyweight",
        "dimensions": "[[mass]]"
      }
    ]
  },`

**Comment by fmeurou** [comment]
Fixed in 0.8.0
