### ISSUE TITLE
rates/stats doesn't filter calculations on key

### ISSUE THREAD

**Issue by bobdivinity** [fmeurou/geocurrency#9]
I've created custom rates with value = 50 for october 2020, you can see them with this request :
`curl -X GET "https://dev.geocurrency.me/rates/?key=46867" -H "accept: application/json" -H "Authorization: <API_KEY>" -H "X-CSRFToken: ygV6vkdAmbe9LmrKELiMeknyNBUSBFpr1KMEzdtdds98Q8so1CDlMFRJC7xojGfE"`

Then, I want to get stats for this month. So i'm using this request :
`curl -X GET "https://dev.geocurrency.me/rates/stats/?key=46867&from_obj=2020-10-01&to_obj=2020-10-31&currency=GBP&base_currency=USD" -H "accept: application/json" -H "Authorization: <API_KEY>" -H "X-CSRFToken: ygV6vkdAmbe9LmrKELiMeknyNBUSBFpr1KMEzdtdds98Q8so1CDlMFRJC7xojGfE"`

I get this response :
`{
      "currency": "GBP",
      "base_currency": "USD",
      "period": "2020-10",
      "avg": 0.7743377906,
      "max": 0.7743377906,
      "min": 0.7743377906,
      "std_dev": 0
 }`

I should get an average at 50.

Now, If i'm doing this request without specify key, i'm getting :
`{
      "currency": "GBP",
      "base_currency": "USD",
      "period": "2020-10",
      "avg": 40.30190609719487,
      "max": 50,
      "min": 0.7743377906,
      "std_dev": 19.093627498761194
}`

Here, i'm getting stats for any values of key

**Comment by fmeurou** [comment]
Fixed in latest version
